server:
  port: 8090
spring:
  data:
    mongodb:
      username: thentrees
      password: thentrees
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin